name: 'Deploy to AWS S3'
description: 'Deploy a static website to AWS S3 bucket'
inputs: # we will extract them in my-main.js file
  bucket:
    description: 'Name of the S3 bucket'
    required: true
  bucket-region:
    description: 'Region of the S3 bucket'
    required: false
    default: 'us-east-1'
  dist-folder: # path to the files that should be uploaded to the bucket
    description: 'Folder containing the static files'
    required: true

outputs:
  website-url:
    description: 'URL of the deployed website' # we register the output, but we will set a value in my-main.js

runs:
  using: 'node20'
  main: 'my-main.js'