name: 'Get & Cache Dependencies'
description: 'Get and cache dependencies for faster builds'

inputs:
  my-caching:
    description: 'Cache dependencies'
    required: false
    default: 'true'

outputs:
  my-used-cache:
    description: 'Whether cache was used'
    value: ${{ steps.my-install-step.outputs.my-cache-key }}

runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.my-caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: my-install-step
      if: steps.cache.outputs.cache-hit != 'true' || inputs.my-caching != 'true'
      run: |
        npm ci # providing shell:bush must when using 'run'
        echo "my-cache-key='${{ inputs.my-caching }}'" >> $GITHUB_OUTPUT
      shell: bash